# Generated by Django 4.2.21 on 2025-05-26 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricoCompra',
        ),
    ]
