# Generated by Django 4.2.21 on 2025-05-27 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicocompra',
            name='itens',
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='mercado.historicocompra')),
            ],
        ),
    ]
